### PR TITLE
Review and Update pt_br translation (Compendium 87,4%)

### PR DESCRIPTION
**Pull request by Mikeliro**
- Added subtitle translation
- Adaptation of names to be compatible with the compendium
- abyssal chasm compendium [100%]
- forlorn hollows compendium [100%]
- magnetic caves compendium [100%]
- primordial caves compendium [37%]
- toxic caves compendium [100%]

### CODE REVIEW

**Comment by Deescafeinado** [comment]
what do u mean “adaptation of names to be compatible”? i traslated the items already. If u want make the compendium, it’s yours, but keep my work intact please.

**Comment by Mikeliro** [comment]
> what do u mean “adaptation of names to be compatible”? i traslated the items already. If u want make the compendium, it’s yours, but keep my work intact please.

I had already translated everything. I ended up naming the file as ".lang" instead of ".JSON"

**Comment by Mikeliro** [comment]
> what do u mean “adaptation of names to be compatible”? i traslated the items already. If u want make the compendium, it’s yours, but keep my work intact please.

With “adaptation of names to be compatible” I meant that when translating the compendium I modified some names in my translation to better adapt to the context.

**Comment by Deescafeinado** [comment]
dont care, i finished and requested the merge first. (he wants to change what i translated already)

**Pull request merged**
